language: python
python:
  - '3.8'
script:
  - python example.py
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: api
  target_branch: gh-pages
